baseurl = "https://cfelder.com/"
title = "Christian Felder"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
#disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-666008-4"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  sideBarTitle = "👋🏻 I create stuff"
  description = "Christian is a developer, analogue photographer, ramen lover, glider pilot."
  copyright = ""
  sidebarAbout = [
    "Besides that, Christian is a developer, analogue photographer, ramen lover, glider pilot.",
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = ""
  disableRSS = true
  disableSitemap = true

  # Nav links in the side bar
#  [[params.navlinks]]
#  name = "Home"
#  url = ""
#
#  [[params.navlinks]]
#  name = "About"
#  url = "about/"
#
#  [[params.navlinks]]
#  name = "Get in touch"
#  url = "contact/"

  [params.social]
  #facebook      = "full page or profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #email         = "email@example.com"
  twitter       = "https://twitter.com/masone"
  linkedin      = "https://www.linkedin.com/in/christian-felder-363a7ab8"
#  stackoverflow = "full profile url in stackoverflow"
  instagram     = "https://instagram.com/masone"
  github        = "https://github.com/masone"
